project:
  type: book
  output-dir: docs

book:
  title: "Readings in Causal Inference, Fall 2023"
  author: "Christian Testa"
  repo-url: https://github.com/ctesta01/CausalFall2023
  chapters:
    - index.qmd
    - 1983_Rosenbaum_and_Rubin/1983_Rosenbaum_and_Rubin.qmd
    - 2000_Robins_Hernan_and_Brumback/2000_Robins_Hernan_and_Brumback.qmd
    - 2000_Dawid/2000_Dawid.qmd
    - 2019_Aronow_Miller/2019_Aronow_Miller.qmd
format:
  html:
    toc: true
    theme: style.scss
    number-depth: 1
    toc-expand: 3
  pdf:
    documentclass: scrreport