---
title: "Readings in Causal Inference, Fall 2023"
format: 
  html:
    theme: style.scss
---

## Introduction

During the Fall 2023 I'm doing a reading-based independent study 
and writing up my notes to share here from some classic and modern 
texts in causal inference with a particular interest on a few subtopics
including 1) complex mediators, 2) the role of semiparametric methods,
and 3) doubly-robust learning.

::: {.callout-tip collapse="true"}
## Reading List for the Semester

{{< include reference_table.qmd >}}

{{< include additional_references.qmd >}}
:::

## Writeups 

--- 

Week 1: <a href="1983_Rosenbaum_and_Rubin/1983_Rosenbaum_and_Rubin.html" style='text-decoration: none; color: black;'><u><i>The Central Role of the Propensity Score in Observational Studies for Causal Effects</i></u> by Paul R. Rosenbaum and Donald B. Rubin (1983), Biometrika</a>

[HTML](1983_Rosenbaum_and_Rubin/1983_Rosenbaum_and_Rubin.html) 
<span style='margin-left: 25px;'></span>
[PDF](1983_Rosenbaum_and_Rubin/1983_Rosenbaum_and_Rubin.pdf)
---

Week 2a: <a href="2000_Robins_Hernan_and_Brumback/2000_Robins_Hernan_and_Brumback.html" style='text-decoration: none; color: black;'><u><i>Marginal Structural Models for Causal Inference</i></u> by James M. Robin, Miguel Ángel Hernán, and Babette Brumback (2000), Epidemiology</a>

[HTML](2000_Robins_Hernan_and_Brumback/2000_Robins_Hernan_and_Brumback.html) 
<span style='margin-left: 25px;'></span>
[PDF](2000_Robins_Hernan_and_Brumback/2000_Robins_Hernan_and_Brumback.pdf)
---

Week 2b: <a href="2000_Dawid/2000_Dawid.html" style='text-decoration: none; color: black;'><u><i>Causal Inference Without Counterfactuals</i>
</u> by Alexander Phillip Dawid (2000). JASA</a>

[HTML](2000_Dawid/2000_Dawid.html)
<span style='margin-left: 25px;'></span>
[PDF]()

---

Week 3: <a href="2019_Aronow_Miller/2019_Aronow_Miller.html" style='text-decoration: none; color: black;'><u><i>Foundations of Agnostic Statistics</i>
</u> by Peter M. Aronow and Benjamin T. Miller (2019). Cambridge University Press.</a>

[HTML](2019_Aronow_Miller/2019_Aronow_Miller.html)
<span style='margin-left: 25px;'></span>

---

Week 4: <a href="2019_Nabi_Shpitser/2019_Nabi_Shpitser.html" style='text-decoration: none; color: black;'><u><i>Fair Inference on Outcomes</i>
</u> by Razieh Nabi and Ilya Shpitser (2019) for The Thirty-Second AAAI Conference on Artificial Intelligence.</a>

[HTML](2019_Nabi_Shpitser/2019_Nabi_Shpitser.html)
<span style='margin-left: 25px;'></span>

---

Week 5: <a href="2011_targeted_learning_I/2011_targeted_learning_I.html" style='text-decoration: none; color: black;'><u><i>Targeted Learning: Causal Inference on Observational and Experimental Outcomes</i>
</u> by Mark J. van der Laan and Sherri Rose (2011).</a>

[HTML](2011_targeted_learning_I/2011_targeted_learning_I.html)
<span style='margin-left: 25px;'></span>

